# Generated by Django 4.1.2 on 2022-10-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_email_users_is_superuser_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='NONAME', max_length=100),
        ),
    ]
