# Generated by Django 4.1.2 on 2022-11-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_is_active_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={
                'verbose_name': '=Пользователя=',
                'verbose_name_plural': '=Пользователи='
            },
        ),
    ]
