# Generated by Django 4.1.2 on 2022-11-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_tasks_author_alter_tasks_executor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={
                'verbose_name': '=Задачу=',
                'verbose_name_plural': '=Задачи='
            },
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='labels',
        ),
        migrations.CreateModel(
            name='TaskRelationLabel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('label', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='labels.labels')),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='tasks.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(
                blank=True,
                related_name='label',
                through='tasks.TaskRelationLabel',
                to='labels.labels'),
        ),
    ]
